apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: dalvms.xvm.dal.ca
spec:
  group: xvm.dal.ca
  names:
    kind: DalVM
    plural: dalvms
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
                  enum:
                    - web-app
                    - ml-app
                    - internal-app
                os:
                  type: string
                  enum:
                    - mac
                    - windows
                    - linux
              required:
                - size
                - os
  claimNames:
    kind: VMClaim
    plural: vmclaims
